export const FETCH_REPOS_REQUEST = "FETCH_REPOS_REQUEST";
export const FETCH_REPOS_SUCCESS = "FETCH_REPOS_SUCCESS";
export const FETCH_REPOS_FAILURE = "FETCH_REPOS_FAILURE";
export const FETCH_REPOS_COUNT_REQUEST = "FETCH_REPOS_COUNT_REQUEST";
export const FETCH_REPOS_COUNT_SUCCESS = "FETCH_REPOS_COUNT_SUCCESS";
export const FETCH_REPOS_COUNT_FAILURE = "FETCH_REPOS_COUNT_FAILURE";
